sudo: required
services: 
  - docker

before_install:
  - docker build -t nkhaitov/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true nkhaitov/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: elasticbeanstalk-us-west-1-096269405598
  bucket_path: docker-react
  on : 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

